const BAD_REQUEST_ERROR = 400;
const UNAUTHORIZED_ERROR = 401;
const NOT_FOUND_ERROR = 404;
const UNEXPECTED_ERROR = 500;
const SECRET_KEY = 'E4t%y&ui*k';

module.exports = {
  BAD_REQUEST_ERROR,
  UNAUTHORIZED_ERROR,
  NOT_FOUND_ERROR,
  UNEXPECTED_ERROR,
  SECRET_KEY,
};
